server:
  port: 8080

spring:
  application:
    name: aoc-se
  profiles:
    active: local
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

  flyway:
    enabled: true

cognito:
  region: ap-northeast-2

management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: never